[tool.commitizen]
gpg_sign = true
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
ignored_tag_formats = ["*.post*"]
version = "8.1.50.post2"
update_changelog_on_bump = true
version_files = [
  "ignition-api/setup.cfg:version",
  "ignition-api-stubs/pyproject.toml:version"
]
