[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools>=42",
  "wheel",
]

[tool.isort]
profile = "black"
py_version = 27

[tool.mypy]
python_version = 2.7

[tool.pydocstyle]
convention = "google"
add_ignore = ["D205", "D415"]
match_dir = "system"
